### PR TITLE
ENH move to new CLI

### PR DESCRIPTION
**Pull request by beckermr**
This PR moves to the new CLI and stops updating versions twice.

### CODE REVIEW

**Comment by CJ-Wright** [comment]
Is this ready?

**Comment by beckermr** [comment]
Waiting on circle ci to come back: https://status.circleci.com/

**Comment by viniciusdc** [comment]
Circle started hourly jobs

**Comment by beckermr** [comment]
yeah that's fine

**Comment by beckermr** [comment]
I put in a change in this PR so it doesn't do that anymore.

**Comment by beckermr** [comment]
looks like we are good to merge

**Pull request merged**
