### PR TITLE
run audit job

### PR DESCRIPTION
**Pull request by CJ-Wright**
Actually start running the audit jobs

### CODE REVIEW

**Comment by CJ-Wright** [comment]
CC @beckermr

**Comment by CJ-Wright** [comment]
The audit information is getting its [own folder](https://github.com/regro/cf-scripts/blob/master/conda_forge_tick/audit.py#L73) with no modification to the graph itself. My hope is that since they are seperate git will be smart enough to merge them properly.
See https://github.com/regro/cf-scripts/pull/975 for updates

**Comment by CJ-Wright** [comment]
Do the jobs get their own filesystems?

**Comment by beckermr** [comment]
Git can do the merge, but I think we need to make sure the right commands are there in the bot code when it pulls and pushes. My git fu is weak so IDK exactly what these are.

**Comment by beckermr** [comment]
I checked the deploy command and it seems ok

**Comment by beckermr** [comment]
You may need to add the audit dir to the deploy command

**Comment by CJ-Wright** [comment]
That's a good catch!

**Comment by CJ-Wright** [comment]
fixed here: https://github.com/regro/cf-scripts/pull/976

Note that that PR and this one need to go in on the same bot cycle.

**Comment by beckermr** [comment]
Probs best to stop the bot and restart then. Delete the please.go file on master and it should stop.

**Comment by CJ-Wright** [comment]
I'll come back to clean up the actual job next round.

**Pull request merged**
